language: julia
julia:
  - nightly
  - 1.8
  - 1.7
  - 1.6

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.8
      script: |
        julia docs/make.jl --test --deploy
    - stage: Coverage
      julia: 1.8
      script: |
        julia -e '
          using Pkg
          Pkg.add("Coverage")
          using Coverage
          Codecov.submit(process_folder())'
