language: julia
julia:
  - nightly
  - 1.8
  - 1.7
  - 1.6

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using Multivectors
          DocMeta.setdocmeta!(Multivectors, :DocTestSetup, :(using Multivectors); recursive=true)
          doctest(Multivectors)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
